server:
  port: 9296

spring:
  application:
    name: CONFIGURATION-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/VinothkumarSelvaarasan/config-serv/blob/main/application.yml
          clone-on-start: true
  profiles:
    active: native